server:
  port: 8080

agent:
  base-url: http://192.168.2.207/v1/
  connect-timeout: 30
  read-timeout: 300
  write-timeout: 30
  call-timeout: 600
  retry-on-connection-failure-timeout: true

oss:
  type: minio
  endpoint: http://192.168.2.83:9000/
  access-key: admin
  secret-key: 12qw!@QW
  bucket-name: workspace